### ISSUE TITLE
Problem using mercadopago-plugin on Xcode

### ISSUE THREAD

**Issue by brunovinny** [mercadopago/px-ios#1374]
Where can I open an issue  solution request?

**Comment by zehemz** [comment]
Hi! you can fork the project and open a pull request. 

We will evaluate it as soon as possible.

Regards

**Comment by brunovinny** [comment]
@zehemz  I've installed the mercadopago-plugin version 1.1.17 in cordova but when I try to build my project using "ionic cordova build ios" in terminal I get this error: "error: using bridging headers with framework targets is unsupported", besides I get over 170 warnings while building signed app in XCode. May I email you with all error's details?"

**Comment by zehemz** [comment]
@brunovinny I will ask to the team if they are planning to generate a fix version for 1.1 plugin and let you know (sorry about that, I'm android developer actually). I will meet them on monday.

Anyway, from version 1, 1.1.18 is available and you can clone and checkout the project and make the modifications you need.

If you want to get long term support I will recommend to you update the dependency to 3.7.2.

If you have any other doubt please be free to ask.
