### ISSUE TITLE
Xcode 8 iOS 10 - production code

### ISSUE THREAD

**Issue by cruzalex** [mercadopago/px-ios#144]
Is this version working, for production? The other repository, doesn't work with iOS 10 and Xcode 8.
Can we use this version on Xcode 8 and iOS 10? How can we do it?

**Comment by demtej** [comment]
Yes , you can. This version should work with XCode 8. Let me know if you have any problem.

**Comment by rmorbach** [comment]
Not working for me.

**Comment by demtej** [comment]
@rmorbach Which branch are you cloning? Could you try "master"?

**Comment by rmorbach** [comment]
masterWOdependencies seems to be working. Is this version available on CocoaPods?

**Comment by demtej** [comment]
Yes, you can download as version 2.0.3.2.
por 'MercadoPagoSDK', '2.0.3.2'
This version is Swift 2.3 compatible.
Let me know if you have any problem.

**Comment by rmorbach** [comment]
Still not able to build this in Xcode 8. Any forecast for Swift 3.0 compatibility?

**Comment by demtej** [comment]
The main version (2.0.5) is Swift 3.0 compatible.
pod 'MercadoPagoSDK'
Can you provide more information about the problem?
What version of XCode are you using?
Swift or Objective-C?

**Comment by rmorbach** [comment]
My Xcode is Version 8.0 (8A218a) and I'm using Swift. Can you provide a sample project that works in this setting?
