### ISSUE TITLE
Crash in iOS 8.x -`San Francisco` font is available in iOS 9.0+

### ISSUE THREAD

**Issue by nsuarezml** [mercadopago/px-ios#145]
Default font in MercadoPago SDK is `San Francisco Light`, but it is available in iOS 9.0+.

![screen shot 2016-10-01 at 10 09 23](https://cloud.githubusercontent.com/assets/8617954/19014274/59b31b08-87bf-11e6-8ca6-c405fa4852d4.png)

**Comment by demtej** [comment]
Fixed and committed to master.
