### ISSUE TITLE
Framework not working using with pod or manually

### ISSUE THREAD

**Issue by guidupas** [mercadopago/px-ios#1489]
### Tipo de componente utilizado
1: Using pod as suggested:
`source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
pod 'MercadoPagoSDK', '3.7.2'`

2: Downloading manually as suggested

3: Trying to create a fat framework using the file in the MarcadoPagoSDK folder

### Comportamiento Esperado
1: Being able to import the library

2: Being able to import the library

3: Being able to import the library or build the framework

### Comportamiento Actual
1: I am not able to use the version 3.7.2 in pod file. It doesn't find tis version. I had to install the version 3.7.0. After using pod to install the version 3.7.0 and opening the workspace I cannot import it. It doesn't show the SDK to import

2: Something. After following al the steps suggested to use it downloading manually, I cannot import the SDK. It doesn't show to import

3: First I was being able to build it successfully and I was able to import the .framework to my project but when I tried to find MercadoPagoContext it didn't appear. The only thing that appeared was a function to detect the MercadoPagoVersion

Now when I try to build the framework again it shows me this message:
`** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)`

**Comment by juansanzone** [comment]
Hi @guidupas . Please, try with the version "3.7.4"

**Comment by guidupas** [comment]
Hi @juansanzone . I had tried already but I tried again now and it didn't work again.

Podfile

> project 'TesteMercadoPago.xcodeproj'
> 
> target 'TesteMercadoPago' do
>   
>   source 'https://github.com/CocoaPods/Specs.git'
>   
>   use_frameworks!
>   
>   platform :ios, '8.0'
>   
>   pod 'MercadoPagoSDK', '3.7.4'
> end

Pod result

> Analyzing dependencies
> [!] CocoaPods could not find compatible versions for pod "MercadoPagoSDK":
>   In Podfile:
>     MercadoPagoSDK (= 3.7.4)
> 
> None of your spec sources contain a spec satisfying the dependency: `MercadoPagoSDK (= 3.7.4)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by G1L21088** [comment]
i had the same problem when i use MercadoPagoSDK with CocoaPods don't let me to run my project because found errors on MercadoPago i had to review those errors manually but neither work

**Comment by guidupas** [comment]
Hello @G1L21088 . The same with me here. I even tried to download all the packages separately, compile them individually, create the frameworks and settle all together but the MercadoPagoSDK has a lot of errors. I wasn't able to get it working.

**Comment by G1L21088** [comment]
Hi @guidupas i resolve this bunch of errors and some more that the compiler show later.

![captura de pantalla 2018-06-05 a la s 13 00 10](https://user-images.githubusercontent.com/10768115/41053892-784b54b2-6982-11e8-8593-0259e601d5bf.png)
![captura de pantalla 2018-06-05 a la s 13 00 19](https://user-images.githubusercontent.com/10768115/41053893-785f13b2-6982-11e8-9b0e-f3850944ddd5.png)
![captura de pantalla 2018-06-05 a la s 13 00 26](https://user-images.githubusercontent.com/10768115/41053894-787288de-6982-11e8-9ba3-a00df1cc5380.png)

But i get stuck when this error appear on Objective-C document with extension .m

![captura de pantalla 2018-06-05 a la s 13 03 02](https://user-images.githubusercontent.com/10768115/41053935-971308ea-6982-11e8-8d4a-445235ef6a8d.png)
![captura de pantalla 2018-06-05 a la s 13 03 12](https://user-images.githubusercontent.com/10768115/41053936-972dfeac-6982-11e8-89e5-28460a702a24.png)

**Comment by mayckxavier** [comment]
Same here. Cant run the project with all these errors

**Comment by HernanPaez** [comment]
This project doesn't support Swift 4. As a temporary fix you must override it's settings to use swift 3.3

If you are using cocoapods you can find this under your Pods.xcodeproj

<img width="911" alt="screen shot 2018-06-07 at 14 41 32" src="https://user-images.githubusercontent.com/1944876/41116586-21b03822-6a61-11e8-8304-3aca7bb8a2d4.png">
