### ISSUE TITLE
Xcode solicita cambiar código de Pod a Swift 3

### ISSUE THREAD

**Issue by crisyelpegaso** [mercadopago/px-ios#168]
### Tipo de componente utilizado
Pod de SDK

### Comportamiento Esperado
Abrir proyecto con POD normalmente

### Comportamiento Actual
  Al abrir el proyecto Xcode 8 solicita actualizar el código a Swift 3 cuando ya está migrado

**Comment by fer662** [comment]
@crisyelpegaso pasa con muchas cosas. Podes solucionarlo de tu lado poniendo algo asi al final de tu Podfile

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

**Comment by crisyelpegaso** [comment]
@fer662 muchas gracias por el dato! 
Para crear nuestro pod tuvimos que setear "Use legacy Swift Language Version" en NO para evitar ese error en Xcode 8.1 al descargar la dependencia

**Comment by fer662** [comment]
@crisyelpegaso si, eso es lo que hace el snippet ese en el podfile. Obviamente tenés que hacer pod install después del cambio.
