### ISSUE TITLE
No funciona link terminos y condiciones en iPhone

### ISSUE THREAD

**Issue by demtej** [mercadopago/px-ios#169]
### Tipo de componente utilizado

En F3, dentro de Revisa y confirma cuando seleccionas tarjeta de credito como Payment Method.

### Comportamiento Esperado

Deberia funcionar el link, al igual que funciona con medios off.

### Comportamiento Actual

No anda el link.

**Comment by crisyelpegaso** [comment]
Fixeado en Revamp.
