### ISSUE TITLE
La documentación no es clara sobre cómo mostrar métodos de pago.

### ISSUE THREAD

**Issue by f-martinez11** [mercadopago/px-ios#1731]
Después de revisar la documentación disponible en:

> http://mercadopago.github.io/px-ios/v4/index.html

No encuentro la manera de mostrar métodos de pago distintos a tarjeta de crédito. Me gustaría que al iniciar el proceso de Checkout los usuarios puedan elegir el método e pago que prefieran. Tal y como se muestra en la imagen de la documentación.

![image](https://user-images.githubusercontent.com/16784351/48749275-2eb1ba00-ec48-11e8-8570-4b001dbf89cc.png)

Entiendo que existe la clase llamada `PXPaymentMethodPlugin` pero no es claro cómo agregar el nuevo método.

Gracias.

**Comment by juansanzone** [comment]
Hola @f-martinez11 
Para poder relacionar tu flow de pago con medios de pago (los que queres mostrar al user), en realidad lo que tenes que ver es la creación de la preferencia de pago. 
Lo ideal es que tengas tu preferencia de pago creada, y es ahí donde definis los medios de pago que soportas. (No es algo que configures directo en el SDK). Te recomiendo que revises: https://www.mercadopago.com.ar/developers/es/api-docs/basic-checkout/checkout-preferences/

**Comment by f-martinez11** [comment]
Hola @juansanzone 
Revise lo que me dijiste y no logro obtener que se muestren los otros medios de pago. La preferencia la estoy creando en el servidor utilizando el SDK para NodeJS (https://github.com/mercadopago/dx-nodejs), con el siguiente código:
```
let preference = {
    items: [{
      title: 'Pago de saldo.',
      quantity: 1,
      currency_id: 'COP',
      unit_price: 20000.0
    }],
    payer: {
      email: "test@mail.com"
    },
    payment_methods:{
      excluded_payment_methods: [],
      excluded_payment_types: [],
      default_payment_method_id: "pse"
    }
  }
  return mercadopago.preferences.create(preference);
```
## Al crear la preferencia se obtiene la siguiente respuesta:
```
 "response": {
            "processing_modes": [],
            "binary_mode": false,
            "payment_methods": {
                "excluded_payment_methods": [
                    {
                        "id": ""
                    }
                ],
                "excluded_payment_types": [
                    {
                        "id": ""
                    }
                ],
                "installments": null,
                "default_payment_method_id": "pse",
                "default_installments": null
            },
            "collector_id": **********,
            "operation_type": "regular_payment",
            "items": [
                {
                    "id": "",
                    "picture_url": "",
                    "title": "Pago de saldo.",
                    "description": "",
                    "category_id": "",
                    "currency_id": "COP",
                    "quantity": 1,
                    "unit_price": 20000
                }
            ],
            "payer": {
                "name": "",
                "surname": "",
                "email": "test@mail.com",
                "date_created": "",
                "phone": {
                    "area_code": "",
                    "number": ""
                },
                "identification": {
                    "type": "",
                    "number": ""
                },
                "address": {
                    "street_name": "",
                    "street_number": null,
                    "zip_code": ""
                }
            },
            "back_urls": {
                "success": "",
                "pending": "",
                "failure": ""
            },
            "auto_return": "",
            "client_id": "963",
            "marketplace": "NONE",
            "marketplace_fee": 0,
            "shipments": {
                "receiver_address": {
                    "zip_code": "",
                    "street_number": null,
                    "street_name": "",
                    "floor": "",
                    "apartment": ""
                }
            },
            "notification_url": null,
            "external_reference": "",
            "additional_info": "",
            "expires": false,
            "expiration_date_from": null,
            "expiration_date_to": null,
            "date_created": "2018-11-20T14:02:31.652-04:00",
            "id": "378925295-9b5d5210-21a6-470f-9593-72c93c1b782d",
            "init_point": "https://www.mercadopago.com/mco/checkout/start?pref_id=378925295-9b5d5210-21a6-470f-9593-72c93c1b782d",
            "sandbox_init_point": "https://sandbox.mercadopago.com/mco/checkout/pay?pref_id=378925295-9b5d5210-21a6-470f-9593-72c93c1b782d"
        },
        "status": 201,
        "idempotency": null,
        "pagination": null
```

## Posteriormente, se procede a realizar el Mobile Checkout con el id de la preferencia:
```
  let checkout = MercadoPagoCheckout.init(builder: MercadoPagoCheckoutBuilder.init(publicKey: "TEST-**********", preferenceId: "378925295-9b5d5210-21a6-470f-9593-72c93c1b782d"))
        
        if let myNavigationController = navigationController {
            checkout.start(navigationController: myNavigationController)
        }
```
## En la aplicación al ejecutar la función anterior lo primero que se muestra es la pantalla para ingresar la tarjeta:
Y si se intenta ingresar la tarjeta de prueba para Colombia (4013 5406 8274 6260) https://www.mercadopago.com.co/developers/es/guides/payments/api/testing/ se muestra este error:
![image](https://user-images.githubusercontent.com/16784351/48796271-2354a200-eccd-11e8-8d1c-fc41c1ad4121.png)

Al presionar "More Info":

![image](https://user-images.githubusercontent.com/16784351/48796200-fef8c580-eccc-11e8-8a0d-a1d473623a40.png)

## Nota
Me di cuenta que si abro la url de `sandbox_init_point ` (https://sandbox.mercadopago.com/mco/checkout/pay?pref_id=378925295-9b5d5210-21a6-470f-9593-72c93c1b782d) se ingresa directamente a pago por pse y permite seleccionar los otros medios de pago. Esto me hace creer que el problema no estaría en la preferencia si no en mi implementación del SDK.


![image](https://user-images.githubusercontent.com/16784351/48795887-20a57d00-eccc-11e8-8cdf-75b3eb988325.png)
Espero puedas orientarme sobre lo que puede estar sucediendo.

Gracias.
