### ISSUE TITLE
Volver Para atras de Credito/debito

### ISSUE THREAD

**Issue by edentorres** [mercadopago/px-ios#174]
### Tipo de componente utilizado
F3, en mexico

### Comportamiento Actual
![simulator screen shot nov 7 2016 2 25 23 pm](https://cloud.githubusercontent.com/assets/9399970/20068289/e74a6698-a4f6-11e6-84e7-553d4dc444bb.png)
Se borra el skin y no podes hacer nada

**Comment by crisyelpegaso** [comment]
Pasa lo mismo cuando se selecciona en grupos una tarjeta guardada :
Se borra el skin y aparece el error "Método de pago no soportado".
