### ISSUE TITLE
Doesn't compile on Swift 4.2

### ISSUE THREAD

**Issue by jlubeck** [mercadopago/px-ios#1749]
### Tipo de componente utilizado
pod 'MercadoPagoSDK', '~> 4.0'

### Comportamiento Esperado
It should compile

### Comportamiento Actual
Several errors about deprecations on changes on Swift 4.2 prevent it from compiling

**Comment by juansanzone** [comment]
Hi @jlubeck  ! How are u?
We only support swift 4.0. 
Migration to Swift 4.2 will be planned for the next month. (end of January)

In order to compile our SDK with 4.0 you can add add the following code in your Podfile:

```swift
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['MercadoPagoSDK'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```
