### ISSUE TITLE
Customización de UI

### ISSUE THREAD

**Issue by juanmencacci** [mercadopago/px-ios#1754]
### Tipo de componente utilizado
Estoy usando la lib de **MercadoPago**, el **checkout builder** y quiero **customizar** los **colores**.

### Comportamiento Esperado
Primero probé con el **PXTheme**, pero si lo utilizo, no puedo cambiar los colores de los iconos.
Y si uso el **checkoutColor** solo puedo cambiar eso y no puedo customizar las demás cosas.

### Comportamiento Actual

Usando solo el **PXTheme** no puedo configurar el color de los iconos, seria útil agregar en el **delegado** de **PXTheme** la posible edición de los colores de los iconos.

**Comment by juansanzone** [comment]
Hola Juan!
Qué integración estas haciendo? Si queres danos mas detalles asi te ayudamos a que puedas crear la mejor experiencia.

**Comment by juansanzone** [comment]
Algún update Juan? @juanmencacci
