### ISSUE TITLE
Crash al launchear la app

### ISSUE THREAD

**Issue by LucaKIN** [mercadopago/px-ios#1808]
### Tipo de componente utilizado
Estoy tratando de usar el sdk de mercado pago ios, en una aplicacion react-native ( haciendo manualmente el bridge). 
En un inicio para poder implementar el sdk tuve que agregar el tag use_frameworks!. Leyendo en stackoverflow lei que el problema que tenia podia estar relacionado con la anotacion use_frameworks! y el buildeo de librerias estaticas/dinamicas , por lo tanto actualice cocoapods hasta la version <1.5 para poder evitar usar ese tag. Sin embargo el comportamiento persiste.
### Comportamiento Esperado
Que al archivar el ipa pueda ejecutarlo.
### Comportamiento Actual

Luego de agregar el sdk de mercadopago en cocoapods, archivo el ipa y cuando trato de ejecutarlo se cierra luego de mostrar el splash. En la consola de xcode me esta mostrando el siguiente log:
Won't override system fonts with meli fonts - UIFont
Won't override system fonts with meli fonts - UILabel
Won't override system fonts with meli fonts - UITextView

**Comment by cinder92** [comment]
@LucaKIN yo igual estoy haciendo un bridge para react native, sin embargo me encontré con el problema que al correar la app, me salta un error de que no se encontró el FXBlurView, podrías guiarme en el buen camino?

**Comment by LucaKIN** [comment]
@cinder92 puedo ayudarte a llegar a la misma instancia que yo, subi tu pod file y package.json y te guio.

**Comment by juansanzone** [comment]
@LucaKIN @cinder92 Hola! Inicialmente nosotros no damos soporte oficial para implementación desde react-native. (No son pruebas que hagamos, al menos por ahora) Sí lo hacemos con la full compatibility con Objc. Pueden revisar en nuestro apartado. https://github.com/mercadopago/px-ios#-supported-os--sdk-versions
Si quieren podemos tener la semana que viene una call, para entender bien cómo podemos ayudarlos.

**Comment by LucaKIN** [comment]
@juansanzone gracias por tu respuesta, creo que no tiene que ver con el bridge en si de react-native. En los ejemplos que estan en el proyecto sobre la integracion de mpago en Objc en el archivo podfile solo esta MPAGO con MLUI. En gral nosotros tenemos otros pods agregados en el podfile, por lo que estimo que el problema esta con el manejo de las librerias estaticas vs dinamicas con los tags  `use_modular_headers!` y `use_frameworks!`. Estaria bueno si nos podes dar una explicacion o nos podes guiar respecto a estos temas de como manejarnos para poder integrar el pod de mercado pago con los pods que ya tenemos existentes.

**Comment by juansanzone** [comment]
Dale @LucaKIN . Lo revisamos con el equipo, y te mantenemos el update esta semana!

**Comment by jdnichollsc** [comment]
@juansanzone pregunta, qué puede ser si sale este otro warning?
`2019-03-05 23:43:57.244285-0500 example[53557:715425] PXLog - LazyInit - failureWithCheckout
Error - Validación de preferencia`
Thanks for your help!

**Comment by juansanzone** [comment]
@jdnichollsc Es bastante descriptivo ese log. La preferencia, es lo que deberias tener creado previando (via API) para iniciar efectuar un flujo de pago. Es la llamada (preferencia de pago) prefId.
Si te fijas, para inicializar el checkout, tenes que pasarle tu prefId en el builder:
http://mercadopago.github.io/px-ios/v4/Classes/MercadoPagoCheckoutBuilder.html
Con más detalle en el siguiente init:
http://mercadopago.github.io/px-ios/v4/Classes/MercadoPagoCheckoutBuilder.html#/c:@M@MercadoPagoSDKV4@objc(cs)MercadoPagoCheckoutBuilder(im)initWithPublicKey:preferenceId:

Ese init de arriba deberias utilizar.
Asegurate de estar pasando bien esos parametros. Por algun motivo la preferencia que se esta validando es inválida. Habria que ver que es lo que esta fallando. Pero digamos que es error del lado de la preferencia generada. El SDK en este caso solo efectúa una validación.

Por otro lado. Veo que estas utilizando LazyInit. 
Si queres, podrias abrir otro issue, para tratar este error que estas teniendo, y ahi, pegas bien el código de tu implementación. Porque sin ver cómo estas implementando es dificil. Basate mucho en la documentación de Jazzy publicada en: http://mercadopago.github.io/px-ios/v4/

**Comment by cinder92** [comment]
@LucaKIN perfecto, aqui los dejo

POD

```
source 'https://github.com/CocoaPods/Specs.git'
	use_frameworks!
	platform :ios, '10.0'
	pod 'MercadoPagoSDK', '~> 4.0'
```

packaje.json

```
"react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-navigation": "^2.9.0",
```

**Comment by LucaKIN** [comment]
@juansanzone ya esta solucionado el inconveniente, el problema que estaba teniendo era que cuando archivaba la app crasheaba al abrirse pero no tenia nada que ver con la libreria de mercado pago en si. El problema venia cuando agregaba el anotation use_frameworks! en el podfile de mi proyecto (base c objetivo), con la libreria de FirebaseSDK. Por lo que pude debuggear el ipa archivado, no se estaban compilando bien los modulos nativos. Por otro lado, podrias explicarme un poco mas en detalle como implementar los callbacks en esta version 4? En la anterior version 3.7.2 podiamos simplemente hacer un setPaymentCallbackWithPaymentCallback o setCallbackCancelWithCallback y ya.

**Comment by juansanzone** [comment]
Bien lo damos por cerrado entonces. Si queres escribime a juan.sanzone@mercadolibre.com y vemos en detalle que queres hacer. Y en funcion de eso te ayudamos con lo del callback que decis. Y si algo no esta claro en la docu, aprovechamos y lo actualizamos. Gracias

**Comment by jdnichollsc** [comment]
@juansanzone esos errores podrían devolverlos desde el failureWithChechout para poder mostrar ese mensaje de error desde la app?
Gracias de antemano!

**Comment by juansanzone** [comment]
@jdnichollsc Para errores de inicialización utilizar el protocolo: PXLazyInitProtocol -> http://mercadopago.github.io/px-ios/v4/Protocols/PXLazyInitProtocol.html
Para errores del flujo de pago en si, usuario cancela checkout o el pago se finaliza. PXLifeCycleProtocol -> http://mercadopago.github.io/px-ios/v4/Protocols/PXLifeCycleProtocol.html

**Comment by LuisGarcia9000** [comment]
Hola @LucaKIN, ¿podrías poner la versión de MercadoPagoSDK que usaste y si lo configuraste Manual o por  Podfile?
Ayuda por favor, llevo días intentando hacer que funcione MercadoPago en un proyecto de React-native, pero no logro hacer que compile correctamente mi proyecto.
# Configurandolo por PodFile:
pod 'MercadoPago'

me instala la versión de mercadoPagoSDK, 3.8.0, pero me sale este error: 
../MercadoPagoSDK/MLPXSpinner.m:10:9:
	 'MercadoPagoSDK/MercadoPagoSDK-Swift.h' file not found

# Y Configurandolo manualmente me sale este error:
MercadoPagoSDK/px-ios-release-3.8.0/MercadoPagoSDK/MercadoPagoSDK/InstructionsViewModel.swift:10:8: 
	no such module 'MercadoPagoPXTracking'
	import MercadoPagoPXTracking
	^
	** BUILD FAILED **

**Comment by juansanzone** [comment]
@LuisGarcia9000 No damos soporte para la versión 3. Se quito hace más de medio año ese soporte. Se recomienda migrar a v4. El pod es el que esta en el readme oficial o la documentación de Jazzy.
