### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by jdnichollsc** [mercadopago/px-ios#1818]
### Tipo de componente utilizado
Una interfaz `UITableViewController <UINavigationControllerDelegate, PXLazyInitProtocol, PXLifeCycleProtocol, PXTrackerListener>`

### Comportamiento Esperado
Quisiera poder abrir el checkout de MercadoPago para hacer un simple pago, sin ninguna configuración adicional por el momento.

### Comportamiento Actual
Después de crear la preferencia desde el backend y luego ejecutar el código nativo en Objective C, estoy obteniendo el siguiente error:
```
--Request: Optional(https://api.mercadopago.com/v1/checkout/preferences/98687279-58bdfb33-5863-41d8-97aa-8b9e5c20941a?public_key=BLABLABLA&api_version=1.6)
--Data: {"additional_info":"","auto_return":"","back_urls":{"failure":"","pending":"","success":""},"binary_mode":false,"client_id":"849819765734274","collector":{"tags":["normal","messages_as_seller","messages_as_buyer"]},"date_created":"2019-03-06T09:21:25.461-04:00","expiration_date_from":null,"expiration_date_to":null,"expires":false,"id":"98687279-58bdfb33-5863-41d8-97aa-8b9e5c20941a","init_point":"https://www.mercadopago.com/mco/checkout/start?pref_id=98687279-58bdfb33-5863-41d8-97aa-8b9e5c20941a","internal_metadata":{},"items":[{"id":"","currency_id":"COP","title":"Gorgeous Silk Table","picture_url":"","description":"","category_id":"","quantity":6,"unit_price":95}],"live_mode":true,"marketplace":"NONE","operation_type":"regular_payment","payer":{"phone":{"area_code":"","number":""},"address":{"zip_code":"","street_name":"","street_number":null},"email":"jdnichollsc@hotmail.com","identification":{"number":"","type":""},"name":"","surname":"","date_created":""},"payment_methods":{"default_card_id":null,"excluded_payment_methods":[{"id":""}],"default_installments":null,"default_payment_method_id":null,"excluded_payment_types":[{"id":""}],"installments":null},"processing_modes":[],"sandbox_init_point":"https://sandbox.mercadopago.com/mco/checkout/pay?pref_id=98687279-58bdfb33-5863-41d8-97aa-8b9e5c20941a","shipments":{"receiver_address":{"floor":"","zip_code":"","street_name":"","apartment":"","street_number":null}},"total_amount":570,"site_id":"MCO","brand_name":"Proyecto 26"}
--Error: nil
--Request: Optional(https://api.mercadopago.com/campaigns/check_availability?public_key=APP_USR-acc5b05a-1059-4be6-ba13-2a5038522b3a&email=jdnichollsc%40hotmail.com)
--Data: [{"code":"campaign-doesnt-match","message":"doesn't find a campaign","campaign_id":null}]
--Error: nil
--Request: Optional(https://api.mercadopago.com/v1/px_mobile_api/payment_methods?public_key=APP_USR-acc5b05a-1059-4be6-ba13-2a5038522b3a&amount=570.0&excluded_payment_types=atm,bank_transfer,ticket&site_id=MCO&api_version=1.6&processing_mode=aggregator)
--Request Body: Optional("{\"email\":\"jdnichollsc@hotmail.com\",\"identification\":{\"number\":\"\",\"type\":\"\"}}")
--Data: {"groups":[],"custom_options":[],"payment_methods":[],"cards":[]}
--Error: nil
2019-03-06 08:21:58.846495-0500 example[854:8787] PXLog - LazyInit - finishWithCheckout
```

**Comment by juansanzone** [comment]
Podrias poner todo el código del .m que estas utilizando? @jdnichollsc

**Comment by jdnichollsc** [comment]
Disculpa @juansanzone, fue un error de newbie en Objective C con la inicialización de ese ViewController, tienen algún buen ejemplo?
Estoy haciéndolo así:
```
RNMercadoPagoViewController *ctrl = [RNMercadoPagoViewController new];
[ctrl initWithPublicKey:publicKey preferenceId:preferenceId resolver:resolve rejecter:reject];
UINavigationController *navigator = [[UINavigationController alloc] initWithRootViewController:ctrl];
[navigator setNavigationBarHidden:true animated:false];
...
```

Por cierto, ya estoy obteniendo este otro error:
![captura de pantalla 2019-03-06 a la s 9 12 57 a m](https://user-images.githubusercontent.com/2154886/53888001-6bd06b00-3ff1-11e9-85c1-ee1508c9732b.png)
Thanks in advance!

**Comment by jdnichollsc** [comment]
Al parecer no lo estoy haciendo bien porque obtengo este otro error con este código:
```
[checkout startWithNavigationController:self.navigationController lifeCycleProtocol:nil];
```
<img width="1080" alt="captura de pantalla 2019-03-06 a la s 9 28 54 a m" src="https://user-images.githubusercontent.com/2154886/53888360-50b22b00-3ff2-11e9-80bb-2909885ecab9.png">

**Comment by jdnichollsc** [comment]
Ok, ya corregí el error con el `navigationController`, solo me queda saber porque muestra el error **Payment methods could not be obtained with this preference**

**Comment by juansanzone** [comment]
@jdnichollsc Podrias pasarme la preferenceId y publicKey que estas usando a: juan.sanzone@mercadolibre.com gracias!

**Comment by jdnichollsc** [comment]
Ya pude solucionarlo, gracias!

**Comment by edgarnsr** [comment]
Hola @jdnichollsc Qué solución encontraste con "navigationController"? me está apareciendo el mismo error

**Comment by juansanzone** [comment]
@edgarnsr Asegurense de tener una asoc strong de su navigation ya que en ningun momento nosotros retemos la instancia.

**Comment by jdnichollsc** [comment]
Hola @edgarnsr, desde mi `RNMercadoPagoViewController` tengo esto:
```
- (void)didFinishWithCheckout:(MercadoPagoCheckout * _Nonnull)checkout {
  NSLog(@"PXLog - LazyInit - finishWithCheckout");
  [checkout startWithNavigationController:self.navigationController lifeCycleProtocol:self];
  [self.navigationController setNavigationBarHidden:FALSE];
}
```
Igual traté de venderle el bridge, que quedó muy bien hecho, a MercadoPago pero no quisieron ¯\_(ツ)_/¯

**Comment by edgarnsr** [comment]
Gracias por el apoyo, pude solucionar el problema. Dejo el link de apoyo para futuras referencias [https://stackoverflow.com/questions/12350437/getting-current-uiviewcontroller-in-phonegap#12369091](url)

**Comment by jdnichollsc** [comment]
si, puedes hacerlo más resumido así: `UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:ctrl];`
