### ISSUE TITLE
finishCheckout - missing PXPayment property with Objective C

### ISSUE THREAD

**Issue by jdnichollsc** [mercadopago/px-ios#1822]
### Tipo de componente utilizado
Protocol **PXLifeCycleProtocol**

### Comportamiento Esperado
Poder obtener el PXPayment desde el finishCheckout

### Comportamiento Actual
No veo como se puede obtener este dato, porque agregando ese parámetro muestra el siguiente error:
`Class '...' does not conform to protocol 'PXLifeCycleProtocol'`

**Comment by juansanzone** [comment]
@jdnichollsc Necesitariamos toda la implementación.
Evidentemente estas integrando mal. Si vas a usar el PXLifeCycleProtocol, tenes que pasar como parametro una clase implemente los metodos de PXLifeCycleProtocol. Para poder ayudarte, necesitamos ver toda la integración.

**Comment by juansanzone** [comment]
http://mercadopago.github.io/px-ios/v4/Classes/MercadoPagoCheckout.html#/c:@CM@MercadoPagoSDKV4@objc(cs)MercadoPagoCheckout(im)startWithNavigationController:lifeCycleProtocol:

**Comment by jdnichollsc** [comment]
@juansanzone de esta manera si funciona:
```
- (void (^)(id<PXResult> _Nullable))finishCheckout {
  NSLog(@"PXLog - LazyInit - finishCheckout");
  
  [self _close:@{
    @"type": @"success",
  }];
  return nil;
}
```

Pero mi pregunta es cómo puedo obtener la información del Payment desde ahí? En la documentación no hay ejemplos ni tampoco en el código aquí en GitHub desde Objective C

**Comment by juansanzone** [comment]
Deberias poder leer el PxResult.
Que posee tres metodos:
```
    func getPaymentId() -> String?
    func getStatus() -> String
    func getStatusDetail() -> String
```

**Comment by jdnichollsc** [comment]
Si, ya lo había visto en la definición de esa clase pero el problema es que no sé muy bien Objetive C y no veo como usarlo dentro de ese método 😅

**Comment by juansanzone** [comment]
Lo doy por cerrado al issue, ya que estas conformando bien el protocolo ahora.
Por el resto, si tenes alguna duda con algo de Objc, escribime un correo y te damos una mano.
Saludos

**Comment by jdnichollsc** [comment]
Done!
```
- (void (^)(id<PXResult> _Nullable))finishCheckout {
  return ^ (id<PXResult> _Nullable result) {
    PXPayment *payment = (PXPayment *) result;
    NSLog(payment.description);
  };
}
```

@juansanzone es raro que payment.description no sea igual que la descripción que se obtiene desde Android 🤔

**Comment by MaurixFx** [comment]
Hola me gustaría poder obtener el objeto PXPayment lo estoy implementando en Swift

func finishCheckout() -> ((_ payment: PXResult?) -> Void)? {
        return  ({ (_ payment: PXResult?) in
        
            self.navigationController?.popToRootViewController(animated: false)
        })
 }

**Comment by davidmhHuenei** [comment]
Sos un crack, estaba con el mismo problema y la sintaxis de swift no logro dominarla todavía y no podía obtener la respuesta de la api. Mil gracias!
