### ISSUE TITLE
Customización de Colores

### ISSUE THREAD

**Issue by jsagredo-scott** [mercadopago/px-ios#1823]
### Tipo de componente utilizado
`pod 'MercadoPagoSDK', '4.0.12'` o `pod 'MercadoPagoSDK', '4.0.11'`

### Comportamiento Esperado
que la función builder.setColor(checkoutColor: .red) modifique el color

### Comportamiento Actual

1. Con la versión 4.0.12 no respeta ningún color seteado
2. Con la versión 4.0.11 aparece un color por defecto no proporcionado por el usuario
3. Revisando la versión actual de develop [commit 7263d77](https://github.com/mercadopago/px-ios/tree/7263d77f4756fa830bc86a342480a921a6950b55) esto esta resuelto, pero no esta subido a Cocoapods para poder implementarlo

**Comment by juansanzone** [comment]
@jsagredo-scott Gracias por levantarlo. El lunes haremos una subida el Pod publico, con la actualización! Te avisamos cuando esté!

**Comment by juansanzone** [comment]
@jsagredo-scott Te recomendamos utilizar 4.7.6 . Podes hacer pod repo update, y luego actualizar tu dependencia a la última liberada hoy? 4.7.6. Gracias!

**Comment by juansanzone** [comment]
Algun update @jsagredo-scott ?
