### ISSUE TITLE
[iOS] Framework FXBlurView not found

### ISSUE THREAD

**Issue by cinder92** [mercadopago/px-ios#1824]
### Tipo de componente utilizado

MercadoPago SDK 4

### Comportamiento Esperado

Compilar la aplicación 

### Comportamiento Actual

Al linkear el SDK de MP sale este error, dice que no se encuentra el FXBlurView
![Captura de pantalla 2019-03-09 a la(s) 14 24 01](https://user-images.githubusercontent.com/4725556/54076953-2cb34b80-4277-11e9-818b-981c1fa3eaed.png)

**Comment by juansanzone** [comment]
pudiste solucionarlo @cinder92 ? Deberias probar borrar derived data.

**Comment by grecomatias** [comment]
Hola, tengo el mismo problema, borre derived data y sigo teniendo el mismo error. Alguna sugerencia?
