### ISSUE TITLE
Missing error message from failureWithCheckout method

### ISSUE THREAD

**Issue by jdnichollsc** [mercadopago/px-ios#1828]
### Tipo de componente utilizado
PXLazyInitProtocol/ failure function. Me gustaría poder obtener el mensaje para poderlo mostrar a los usuarios, sería muy útil.

### Comportamiento Esperado
Poder obtener el error del mensaje, no se si mi PR sea suficiente, ya que parece solo obtener el error en **DEBUG**: https://github.com/mercadopago/px-ios/pull/1826/files

### Comportamiento Actual
No hay forma de obtener el mensaje del error.

Gracias de antemano, Nicholls

**Comment by juansanzone** [comment]
@jdnichollsc EL mensaje de error de falla no está pensado para ser user friendly. (Es de negocio) Ni tampoco para ser evaluado y tomar acciones en funcion de ese mensaje. Por eso es que no se retorna. Pero si se printea en consola, para poder debuguearlo. En cuanto a tu PR vamos a evaluarlo en esta semana.

**Comment by jdnichollsc** [comment]
@juansanzone ahhh pero entonces así lo veo muy difícil para identificar errores que llegaran a reportar los usuarios, no? Porque no habría forma de determinar que fue lo que pasó.
Gracias de antemano!
