### ISSUE TITLE
Recordar datos de pago en MercadoPagoCheckout

### ISSUE THREAD

**Issue by jlubeck** [mercadopago/px-ios#1853]
### Tipo de componente utilizado
MercadoPagoSDK 4.0

### Comportamiento Esperado
Cada vez que un mismo usuario intenta hacer un pago, deberia recordar la ultima tarjeta utilizada

### Comportamiento Actual
El usuario tiene que ingresar los datos de la tarjeta cada vez.

Quizas me estoy salteando algun paso en la configuracion, pero no estoy pudiendo hacer que se recuerde los datos de la tarjeta del usuario usando el MercadoPagoCheckout

Es posible?

Gracias

**Comment by GFDaniel** [comment]
Mismo Problema en MercadoPagoSDK 4.18.3

**Comment by juansanzone** [comment]
V4 por el momento no da soporte a esa funcionalidad.
