### ISSUE TITLE
Tela para adicionar cartōes do cliente e salvar o token para cobrar posteriormente

### ISSUE THREAD

**Issue by eduardohf14** [mercadopago/px-ios#1883]
Estou lendo a documentação disponível e procurando em todo lugar, preciso salvar os cartōes do cliente e fazer a cobrança posteriormente pelo meu servidor. Vi que em outras versōes existia uma funcionalidade para isso, porém aparenta não existir mais.

**Comment by juansanzone** [comment]
Ya lo hemos hablado por email.
