### ISSUE TITLE
Do not wait for user to confirm on PXResultViewController to relay PXResult

### ISSUE THREAD

**Issue by fer662** [mercadopago/px-ios#1885]
In our use case we need confirmation of the payment on the client to begin some file uploads. If the user doesn't confirm on the last screen, we never get confirmation and we cannot proceed. The app has no way of knowing the user actually paid and some users just never close the confirmation screen and background the app (yes, our userbase is that special). The app eventually suspends and the payment confirmation got lost in oblivion.
The payment confirmation and the checkout finishing should be 2 separate events.

I'm forking the SDK locally to put a timeout on the screen as a temporary measure.

**Comment by juansanzone** [comment]
@fer662 We are going to check this use case. Make sense. For now you can make a fork and feel free to contact us if you need any help.
