### ISSUE TITLE
Error de validacion SDK JavaScript en WKWebView

### ISSUE THREAD

**Issue by DarioLp** [mercadopago/px-ios#1916]
Se que el issue que estoy subiendo no esta bien ubicado pero sinceramente no sabia bien donde ubicarlo.
Estoy utilizando el SDK JavaScript para desarrollar una aplicacion hibrida en Ionic.
El problema se presenta cuando hago uso de la funcion Mercadopago.createToken, esta me retorna el siguiente error

![imagen](https://user-images.githubusercontent.com/22561247/58705698-55367780-8386-11e9-9d44-b94310fd896f.png)

Este error solo se presenta unicamente utilizando WKWebView, no asi utilizando la version anterior del web view (UIWebView) ni tampoco utilizandolo en android.

No estoy seguro pero creo que esto puede deberse a que cuando se utiliza este web view la aplicacion utiliza una url del estilo "ionic://localhost" para cargar el contenido y esta url no pasaria las validaciones para hacer peticiones a la API.

En caso de ser este el error, este web view no permite cambiar la url por otra aceptada por el sdk(file,http o https) por lo que por ahora no tengo forma de usar el SDK en esta plataforma.

Gracias y perdon por la mala ubicacion del issue.

**Comment by juansanzone** [comment]
Revisar: https://www.mercadopago.com.ar/developers/es/support
