### ISSUE TITLE
[UIApplicationDelegate window]: unrecognized selector sent to instance 0x2828f0700'

### ISSUE THREAD

**Issue by NeriCodec** [mercadopago/px-ios#1991]
### Tipo de componente utilizado
Al intentar utilizar el plugin y abrir el apartados de la tarjeta, el plugin intenta abrir el teclado pero no responde y cierra la app.
### Comportamiento Esperado
Debería mostrar el teclado para escribir el numero de la tarjeta.
### Comportamiento Actual
Se cierra la app al intentar mostrar el teclado en la pantalla de tarjetas.

### ERROR
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GUL_UIApplicationDelegateImpl-390FB4A5-51F3-4449-9CF3-3A3557105BE1 window]: unrecognized selector sent to instance 0x2828f0700' *** First throw call stack: (0x205dc298c 0x204f9b9f8 0x205cdf1c8 0x2326f2220 0x205dc7ed0 0x205dc9e6c 0x1010fb1a4 0x1010fb334 0x205d33a28 0x205d339f4 0x205d32ee8 0x205d32b94 0x205cac474 0x205d32644 0x20671b6f4 0x2324d6378 0x2324d8e44 0x232b5225c 0x232b52708 0x2324d893c 0x2324df784 0x2324d7fac 0x232551280 0x23254a804 0x2326f5a00 0x2326f16e4 0x232b4887c 0x2329ad434 0x1023f6980 0x1023f7a54 0x232122a20 0x232123384 0x232086244 0x23207b640 0x232145f24 0x2321561f4 0x232b51d1c 0x232b28a74 0x232b29048 0x232b290e8 0x20a3113c8 0x2058017d4 0x2057af008 0x205d5432c 0x205d4f264 0x205d4e7c0 0x207f4f79c 0x2326c6c38 0x101f1c044 0x101f19780 0x101f1927c 0x1013bcf54 0x101f18488 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16764 0x101f16804 0x101f022ac 0x1<\M-b\M^@\M-&>`

**Comment by juansanzone** [comment]
Podrias mostrarnos tu implementación ? Y en que versión sistema operativo ocurre? Si querés escribime a juan.sanzone@mercadolibre.com , gracias

**Comment by NeriCodec** [comment]
Yo estoy desarrollando un plugin para Nativescript con mercadopago y todo funciona muy bien, _hipotesis_: el problema pasa cuando existen más plugins que hacen uso del delegate 

https://github.com/NeriCodec/nativescript-mercadopago-px/blob/78e669eb34881dba4b92af4c275bee5a2f476d43/src/mercadopago-px.ios.ts#L35

**Comment by juansanzone** [comment]
@NeriCodec el problema es que no damos soporte para esa implementación que estás haciendo. Que no es nativa. @mminestrelli ¿Podemos ayudarlo?

**Comment by NeriCodec** [comment]
@juansanzone es posible asignarle un delegate al mercadopago, no estoy seguro si esto es posible o si realmente sea el error, ya que el error pasa cuando se quiere sobreponer el teclado para escribir el numero de la tarjeta no se si ahi busca el delegate de la app para hacerlo.

**Comment by NeriCodec** [comment]
Después de hablar con el equipo de Nativescript se llego a este resultado, donde el error se encuentra en su plugin.

https://github.com/NativeScript/ios-runtime/issues/1184#issuecomment-520483195
