### ISSUE TITLE
Botón de pago no funciona al usar scroll para visualizar términos y condiciones

### ISSUE THREAD

**Issue by kim1882** [mercadopago/px-ios#2000]
### Tipo de componente utilizado
MercadoPagoSDK 4.0
### Comportamiento Esperado
El usuario visualiza la pantalla de pago, utiliza la barra de desplazamiento para ver el enlace de términos y condiciones, al intentar presionar el botón de pago, el pago se realiza correctamente
### Comportamiento Actual
El usuario visualiza la pantalla de pago, utiliza la barra de desplazamiento para ver el enlace de términos y condiciones, al intentar presionar el botón de pago, el botón no funciona, no realiza ninguna acción. Este comportamiento SÓLO se presenta al mover el scroll hasta el borde inferior. Si se mueve nuevamente hacia arriba, el botón funciona correctamente de nuevo.

**Comment by juansanzone** [comment]
Por favor probar con la última versión: 4.18.3 
No hemos podido reproducir el escenario.

**Comment by kim1882** [comment]
Ya estamos usando esa versión 
![imagen](https://user-images.githubusercontent.com/5282118/64213510-d3695500-ce72-11e9-9501-fd749f42d420.png)
El problema sólo ocurre si nos desplazamos hasta el borde inferior https://drive.google.com/file/d/1cw8RnyGhUcOkTIyamAfNjTrf9MPR-E95/view?usp=sharing

**Comment by juansanzone** [comment]
@kim1882 escribime por favor a juan.sanzone@mercadolibre.com así podemos ayudarlos con este desarrollo. Por algún motivo no podemos reproducir el escenario con el mismo resultado, pero podemos ayudarlos a ver que está pasando y solucionar el problema para que tengan una integración correcta, y obviamente aplicar el fix si corresponde. 

gracias

**Comment by juansanzone** [comment]
Ya seguimos por email. cierro el issue
