### ISSUE TITLE
Error al querer levantar la app de prueba

### ISSUE THREAD

**Issue by agustinramos** [mercadopago/px-ios#2001]
px-ios/MercadoPagoSDK/Pods/Target Support Files/Pods-MercadoPagoSDK/Pods-MercadoPagoSDK.debug.xcconfig: unable to open file (in target "MercadoPagoSDK" in project "MercadoPagoSDK") (in target 'MercadoPagoSDK')

**Comment by juansanzone** [comment]
@agustinramos porque lo cerraste? pudiste solucionarlo? te podemos ayudar en algo?

**Comment by kevadiya93** [comment]
@agustinramos, 
Estoy enfrentando el mismo problema, ¿puede decirme cómo resolvió este problema?

**Comment by juansanzone** [comment]
Si quieren enviar un video o mas info. Estamos para ayudarlos.
Les recomendamos usar el proyecto de ejemplos de Swift luego de hacer luego de hacer Pod install.

gracias

**Comment by kevadiya93** [comment]
Estoy siguiendo esto

https://github.com/BlackBoxVision/react-native-mercadopago-checkout

El error se produce después de agregar 'MercadoPagoSDK.framework' en la sección 'Embedded Binaries'

**Comment by juansanzone** [comment]
no damos soporte a wraper de react native.
