### ISSUE TITLE
Obtener Clientes en MercadoPagoSDK V4

### ISSUE THREAD

**Issue by GFDaniel** [mercadopago/px-ios#2002]
### Tipo de componente utilizado
MercadoPagoSDK 4.0
### Comportamiento Esperado
En versiones anteriores por medio de MercadoPagoContext y MerchantServer se podía obtener un objeto Customer con las tarjetas del cliente que se encontraban almacenadas en el servidor.
### Comportamiento Actual
En este momento no encuentro como obtener este objeto Customer o cómo obtener esta información (tarjetas) del usuario.

**Comment by juansanzone** [comment]
Esa funcionalidad se deprecó en V4. Y no se da soporte para esa funcionalidad ya que V4 esta enfocada 100% a flujo visual.
Para tener esa funcionalidad podrás seguir utilizando la versión v3 o mercado pago services. (de los cuales ya no se da soporte)

https://cocoapods.org/pods/MercadoPagoServices
o apuntar al tag de v3. 
https://github.com/mercadopago/px-ios/releases/tag/3.8.0
