### ISSUE TITLE
Obtener información de la tarjeta desde el usuario - MPStepBuilder

### ISSUE THREAD

**Issue by GFDaniel** [mercadopago/px-ios#2003]
### Tipo de componente utilizado
MercadoPagoSDK 4.0
### Comportamiento Esperado
Para obtener información sobre la tarjeta desde el usuario y agregar la tarjeta, se usaba la clase **MPStepBuilder** con su método **startCreditCardForm**.
### Comportamiento Actual
Ahora no encuentro una manera de realizar esto.

**Comment by juansanzone** [comment]
v4 no tiene soporte para ese comportamiento.
