### ISSUE TITLE
Integracion  Mobile Checkout - preferenceId

### ISSUE THREAD

**Issue by GFDaniel** [mercadopago/px-ios#2004]
### Tipo de componente utilizado
MercadoPagoSDK 4.0
### Comportamiento Esperado
Estoy integrando Mobile Checkout a mi aplicacion y cuando inicio con “MercadoPagoCheckoutBuilder.init()” tengo que enviar como parámetro 
“preferenceId”. como puedo obtener este dato?

**Comment by juansanzone** [comment]
Hola Daniel, aqui se explica como generar una pref de pago.
https://www.mercadopago.com.ar/developers/es/reference/preferences/_checkout_preferences/post/

Básicamente ahi se agrupa, que vas a pagar, a quien y como.
saludos
