### ISSUE TITLE
Error - Missing translation

### ISSUE THREAD

**Issue by GFDaniel** [mercadopago/px-ios#2005]
### Tipo de componente utilizado
MercadoPagoSDK 4.0
### Comportamiento Esperado
Terminar el proceso de Checkout.
### Comportamiento Actual
Estoy implementando el pago por  MOBILE CHECKOUT después de llenar la sección CARD HOLDER DOCUMENT (introduciendo el tipo y numero) genera el siguiente error:

--Error: nil
Fatal error: Missing translation for: total_row_title_default: file /Users/.../MercadoPagoSDK/Core/Localize/Localizator.swift, line 117

**Comment by frankpc13** [comment]
Al parecer este problema se presenta cuando el dispositivo esta en Ingles, también tengo ese problema

**Comment by GFDaniel** [comment]
Cambie el idioma y funciono, Muchas gracias Frank.
