### ISSUE TITLE
UIWebView deprecation warning.

### ISSUE THREAD

**Issue by fer662** [mercadopago/px-ios#2045]
Apple has stated that it will in the near future stop accepting apps that use UIWebView. Migration to WKWebView is to allow apps to submit past that unknown deadline.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by juansanzone** [comment]
Thanks. I'll check.
@ericertlMELI

**Comment by ericertlMELI** [comment]
Replaced on https://github.com/mercadopago/px-ios/commit/2f478ce2b3b3fceada02766f21c53f29dbde160d
