### ISSUE TITLE
UIWebView Deprecado - Apple rechaza las compilaciones

### ISSUE THREAD

**Issue by bfacumat** [mercadopago/px-ios#2083]
Estamos intentando publicar una aplicacion utilizando la version 4.18.3 del SDK y apple lo rechaza porque el componente UIWebView se encuentra deprecado.
En la version 4.25 este problema se encuentra solucionado, pero no puedo instalar esta version como dependencia de CocoaPods porque no esta disponible, la misma se encuentra marcada como "Private Release"

¿Como se puede solucionar? ¿Tienen alguna fecha estimada de actualizacion del SDK a una version mas reciente?

**Comment by juansanzone** [comment]
Hola Facu., Ahi te liberamos en unos minutos una version para que puedas usar

**Comment by juansanzone** [comment]
@bfacumat:

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  MercadoPagoSDK (4.28) successfully published
 📅  December 10th, 21:00
 🌎  https://cocoapods.org/pods/MercadoPagoSDK
 👍  Tell your friends!

**Comment by juansanzone** [comment]
@bfacumat avisame como fue, asi cerramos el issue. o cualquier otra cosa.
saludos

**Comment by bfacumat** [comment]
@juansanzone si, ya no aparece mas el mensaje al subir las compilaciones, lo podemos cerrar.

Gracias por la rapida respuesta!

**Comment by juansanzone** [comment]
excelente
