### ISSUE TITLE
Se carga mal la tarjeta

### ISSUE THREAD

**Issue by edentorres** [mercadopago/px-ios#215]
### Tipo de componente utilizado
Cuando inicias un flujo con una preferencia que excluya todo salvo tarjeta se ve mal la tarjeta

**Comment by edentorres** [comment]
![simulator screen shot dec 1 2016 4 31 25 pm](https://cloud.githubusercontent.com/assets/9399970/20809081/abf4e082-b7e3-11e6-9961-1fdbe1df5fbc.png)

**Comment by crisyelpegaso** [comment]
Deja de suceder desde 2.2.6
