### ISSUE TITLE
[Issue] - Missing Translations

### ISSUE THREAD

**Issue by JonatanSalas** [mercadopago/px-ios#2230]
¡Gracias x el SDK que desarrollaron, la experiencia y la facilidad de integración son espectaculares!

No quería dejar de mencionarlo, porque siempre se abren issues sin previo agradecimiento, algo que me parece importante hacer. 

Dejo los datos sobre el issue:

### Tipo de componente utilizado

- **SDK**: MercadoPago SDK v4.32.4
- **Medio de Instalación**: CocoaPods

### Comportamiento Esperado

Se espera que el checkout tenga todas las translations. 

### Comportamiento Actual

Al momento de ejecutar el checkout faltan las translations de: 

- **total_row_title_default**
- **card_form_previous_button**
- **security_code**
- **review_change_payment_method_action**
- **review_terms_and_conditions**

Son algunas de las que vi actualmente faltando por una cuestión de que estuve probando el flujo de tarjetas de crédito nomás. 

Para ponerlos un poco más en contexto respecto de esto, el issue se está dando en una integración que estoy armando de este SDK para poder llamarlo desde React Native.

Tengo el repositorio con la librería privado, pero estoy dispuesto a abrirlo y poner a disposición cualquier dato necesario para poder lograr que este inconveniente se solucione.

**No creo que se un problema de configuración, debido a que el SDK y el resto de las translations levantan sin problemas.**

Adjunto capturas:

<img width="415" alt="2" src="https://user-images.githubusercontent.com/7697196/83763213-dd60f400-a64e-11ea-88a3-23ee6788483e.png">
<img width="411" alt="1" src="https://user-images.githubusercontent.com/7697196/83763232-e18d1180-a64e-11ea-9bb3-88a167f9b53d.png">
<img width="410" alt="3" src="https://user-images.githubusercontent.com/7697196/83763239-e225a800-a64e-11ea-9683-b49cf9477215.png">
<img width="411" alt="4" src="https://user-images.githubusercontent.com/7697196/83763246-e2be3e80-a64e-11ea-9b1f-f55a1280588e.png">

**Comment by JonatanSalas** [comment]
Cierro, dado a que pude resolver el incidente.

**Comment by santiagoatella** [comment]
Como pudiste resolverlo? Gracias!

**Comment by bfacumat** [comment]
@JonatanSalas como pudiste resolverlo?

**Comment by yonemec** [comment]
@bfacumat 
@santiagoatella 
Buenas..  Como resolvieron el problema?

**Comment by bfacumat** [comment]
@yonemec Tenes que agregar un archivo de localizacion para español. Yo lo hice siguendo este post https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881, una vez que tengas el archivo agregas todos los textos que aparecen sin traducir, te paso un ejemplo.

![Captura de Pantalla 2022-10-10 a la(s) 10 14 26](https://user-images.githubusercontent.com/1767694/194875394-6b4cffc5-99dc-49e0-84ef-f4ad7d1d422b.png)

Espero te sea de ayuda

**Comment by yonemec** [comment]
> @yonemec Tenes que agregar un archivo de localizacion para español. Yo lo hice siguendo este post https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881, una vez que tengas el archivo agregas todos los textos que aparecen sin traducir, te paso un ejemplo.
> 
> ![Captura de Pantalla 2022-10-10 a la(s) 10 14 26](https://user-images.githubusercontent.com/1767694/194875394-6b4cffc5-99dc-49e0-84ef-f4ad7d1d422b.png)
> 
> Espero te sea de ayuda



> @yonemec Tenes que agregar un archivo de localizacion para español. Yo lo hice siguendo este post https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881, una vez que tengas el archivo agregas todos los textos que aparecen sin traducir, te paso un ejemplo.
> 
> ![Captura de Pantalla 2022-10-10 a la(s) 10 14 26](https://user-images.githubusercontent.com/1767694/194875394-6b4cffc5-99dc-49e0-84ef-f4ad7d1d422b.png)
> 
> Espero te sea de ayuda

@bfacumat  Muchisimas Gracias!!
