### ISSUE TITLE
122 Buildtime warnings

### ISSUE THREAD

**Issue by Macacoazul01** [mercadopago/px-ios#2326]
Estou usando a última versão pública do sdk para iOS: 
pod 'MercadoPagoSDK', '4.32.4'

E quando faço a build no Xcode aparecem 122 warnings nas bibliotecas do mercado pago:
![Captura de Tela 2020-09-01 às 11 56 10](https://user-images.githubusercontent.com/57464965/91867608-350cfc80-ec4a-11ea-8c2d-64beea0d2e96.png)

Tudo funciona bem com o pagamento apesar disso.

Vi que existem versões mais atualizadas do SDK (se não me engano a última é a 4.35.6), elas não estão disponíveis para uso? Corrigem esses warnings?

**Comment by ericertlMELI** [comment]
Hola @Macacoazul01, estamos trabajando en una nueva version publica de MercadoPagoSDK y esperamos hacer el release en la primer mitad de 2021. Saludos
