### ISSUE TITLE
No buildea

### ISSUE THREAD

**Issue by SonicGerkor** [mercadopago/px-ios#2363]
### Tipo de componente utilizado

Hice pod install con pod 'MercadoPagoSDK'
Estoy usando Swift 4.2, iOS version 11

### Comportamiento Esperado

Que la aplicación buildee

### Comportamiento Actual

El SDK no buildea, tira el siguiente error

![image](https://user-images.githubusercontent.com/22029386/98445025-1fa5ca00-20f4-11eb-8576-20643edf08ff.png)

**Comment by ericertlMELI** [comment]
Hola @SonicGerkor, ese error ya deberia estar resuelto. Si no es asi, reabri este issue
Saludos
