### ISSUE TITLE
Localization Error

### ISSUE THREAD

**Issue by SonicGerkor** [mercadopago/px-ios#2370]
### Tipo de componente utilizado

Ultima versión de la lib, le seteo el language como "es" o "en"

### Comportamiento Esperado

Que este bien localizado

### Comportamiento Actual

Solo localiza algunas partes del flujo.

![image](https://user-images.githubusercontent.com/22029386/99156536-4dfd4980-26a0-11eb-9725-31447e96d29c.png)

**Comment by ericertlMELI** [comment]
Hola @SonicGerkor, actualmente estamos haciendo una reestructuracion de la lib publica por lo que no estamos sacando nuevas versiones. Mientras eso suscede, para resolver tu inconveniente, podes agregar esas keys a un archivo de idiomas local (Localizable.strings)

**Comment by grago** [comment]
Hola @ericertlMELI estoy teniendo problemas similares, intenté agregar las keys al Localizable.strings del proyecto como sugeriste, pero no los toma. Adicionalmente hay algunos íconos que no muestra (tales como los íconos de tarjeta de crédito, débito, etc.)

Existe actualmente una solución para este problema? Muchas gracias!
