### ISSUE TITLE
Instalacion con Cocoapods 1.10.0 falla en nuevo proyecto fresco

### ISSUE THREAD

**Issue by lucasrueda** [mercadopago/px-ios#2386]
### Tipo de componente utilizado

Pasos para reproducir:
1. Crear nuevo proyecto simple con Xcode 11.6
2. Correr ``` pod init ``` en la carpeta del proyecto
3. Agregar ``` pod 'MercadoPagoSDK' ``` al Podfile
4. Correr ``` pod install ```
### Comportamiento Esperado

Instalacion exitosa

### Comportamiento Actual

```
The 'Pods-project' target has transitive dependencies that include statically linked binaries: (MLCardForm)
```
![image](https://user-images.githubusercontent.com/24287521/103427335-26eece80-4b9f-11eb-9a3f-0a9d3e9fd267.png)

**Cosas que ya probe:**
- Utilizar el plugin 'cocoapods-clean_build_phases_scripts', comentar linea ``` use_frameworks! ``` y agregar ``` use_modular_headers! ```
![image](https://user-images.githubusercontent.com/24287521/103430424-ae8a0c80-4ba2-11eb-8ee9-f5ca02471aaf.png)

Error que da cuando hacemos esto:

1. AndesUI.modulemap not found
``` module map file '/Users/lrueda/Library/Developer/Xcode/DerivedData/melinew-..../Debug.../AndesUI/AndesUI.modulemap' not found ```
2. Missing required module 'SwiftShims'
![image](https://user-images.githubusercontent.com/24287521/103430453-0b85c280-4ba3-11eb-80ce-301578e10281.png)

**Comment by lautaropaske** [comment]
¿Es posible que este problema se resuelva con [este merge](https://github.com/mercadopago/px-ios/pull/2365/files)?

**Comment by lautaropaske** [comment]
@jscaramal-meli

**Comment by ericertlMELI** [comment]
Hola Lautaro. Para resolver esto, asegurate que en MercadoPagoSDK.podspec esta linea exista y no este comentada con un #

`s.static_framework = true`

**Comment by lautaropaske** [comment]
Hola @ericertlMELI! Gracias por tu respuesta. Efectivamente, esa línea no está. 

MLCardForm tiene esta línea desde la versión [0.9.2](https://cocoapods.org/pods/MLCardForm#v092), pero la última versión disponible al público de MercadoPagoSDK, [4.32.4](https://cocoapods.org/pods/MercadoPagoSDK), usa MLCardForm 0.1.

¿Para que este problema se resuelva deberíamos esperar al próximo release público de MercadoPagoSDK?

**Comment by ericertlMELI** [comment]
Si, habria que esperar al proximo release publico. Mientras eso suceda imagino que podes forzar en tu podfile la version de MLCardForm a 0.9.1, y MLCardDrawer a 1.5.1

**Comment by lautaropaske** [comment]
Funcionó @ericertlMELI, gracias!

**Comment by ericertlMELI** [comment]
Genial, cierro el issue
