### ISSUE TITLE
No se puede integrar el pod

### ISSUE THREAD

**Issue by lugola** [mercadopago/px-ios#2396]
Hola a todos, tengo un problema, no deja integrar el pod o algo esta pasando... hago un pod Install supuestamente lo instala pero al abrir el proyecto no esta el framework 

¿alguna sugerencia?

<img width="963" alt="Captura de Pantalla 2021-01-21 a la(s) 19 10 03" src="https://user-images.githubusercontent.com/15927968/105431957-46b46800-5c1c-11eb-9cad-b759299f58b7.png">

Y al intentar ocuparlo en el viewcontroller no reconoce el pod

<img width="963" alt="Captura de Pantalla 2021-01-21 a la(s) 19 11 33" src="https://user-images.githubusercontent.com/15927968/105432060-7bc0ba80-5c1c-11eb-8b7f-999ec848c257.png">

**Comment by sdkspaymentez** [comment]
Si, tira
"[!] The 'Pods-DoctoDoc' target has transitive dependencies that include statically linked binaries: (MLCardForm and MLCardDrawer)" cuando se está instalando, por ende no logra integrar el pod, te tenés que ir a la última versión que no tiene esos binarios anexados, o sea:

pod 'MercadoPagoSDK', '~> 4.7.0'

**Comment by ftamburri** [comment]
Si, tira: "[!] The 'Pods-DoctoDoc' target has transitive dependencies that include statically linked binaries: (MLCardForm and MLCardDrawer)" cuando se está instalando, por ende no logra integrar el pod, te tenés que ir a la última versión que no tiene esos binarios anexados, o sea:

pod 'MercadoPagoSDK', '~> 4.7.0'
