### ISSUE TITLE
No funcionan las notificaciones IPN

### ISSUE THREAD

**Issue by javenosa** [mercadopago/px-ios#283]
Por favor que alguien conteste sobre este asunto, antes funcionaban OK las notificaciones IPN, tanto en sandbox como no.

https://groups.google.com/forum/#!category-topic/mercadopago-developers/apis/LdIfapsLOOM

**Comment by crisyelpegaso** [comment]
@javenosa este issue corresponde a funcionalidad de backend, no a las SDK mobile, por eso lo cierro.
De todos modos @joelibaceta y el equipo de backend están al tanto del inconveniente y van a responder sobre esto en el developer site en cuanto lo tengan resuelto.
