### ISSUE TITLE
Default installments no anda en CustomerCards

### ISSUE THREAD

**Issue by edentorres** [mercadopago/px-ios#326]
### Tipo de componente utilizado
En f2
### Comportamiento Actual
Seteo default installments e igual me trae el fomulario para seleccionar cuotas

**Comment by crisyelpegaso** [comment]
Pasa lo mismo con preferencias de pago: 
![screen shot 2017-01-02 at 4 25 07 pm](https://cloud.githubusercontent.com/assets/8344291/21595029/1415cbc6-d108-11e6-8c12-8b507d4b4f65.png)

**Comment by edentorres** [comment]
Se fixea en la v3
