### ISSUE TITLE
Falta mapear algunos campos en PaymentMethod

### ISSUE THREAD

**Issue by fernandospr** [mercadopago/px-ios#412]
A [PaymentMethod.swift](https://github.com/mercadopago/px-ios/blob/development/MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift) le faltan campos que tiene el servicio.

El mismo issue fue cargado en el SDK de Android, ver allí la descripción: https://github.com/mercadopago/px-android/issues/271

**Comment by crisyelpegaso** [comment]
Gracias @fernandospr por el comentario. Lo agregamos para la próxima versión, te avisamos apenas salga con la próxima versión, 
Saludos!
