### ISSUE TITLE
Visualización de Navigation no consistente con wallet

### ISSUE THREAD

**Issue by crisyelpegaso** [mercadopago/px-ios#435]
### Tipo de componente utilizado
SDK Completa - Verificar

### Reportado:
- Navigation mas alto(porque rompimos consistencia?)
- Navigation 10 px mas alto fixear (MUST)

**Comment by edentorres** [comment]
Quedaria esto: 
![problema con la animacion](https://cloud.githubusercontent.com/assets/9399970/21983965/786fe82a-dbd2-11e6-9736-151fb39b3447.gif)
