### ISSUE TITLE
Crash al validar un código de seguridad

### ISSUE THREAD

**Issue by nbattelli** [mercadopago/px-ios#436]
El crash ocurre en el método `validateSecurityCodeWithPaymentMethod(:)` de la clase [CardToken.swift](https://github.com/mercadopago/px-ios/blob/development/MercadoPagoSDK/MercadoPagoSDK/CardToken.swift) al validar un código de seguridad con un número de tarjeta de crédito con menos de 6 caracteres.

Esta es la porción de código:
`let range = cardNumber!.startIndex ..< cardNumber!.characters.index(cardNumber!.characters.startIndex, offsetBy: 6)`

**Comment by demtej** [comment]
Podrías facilitarnos la porción de código para saber como estás utilizando la validación?
Gracias por reportarlo!

**Comment by nbattelli** [comment]
Para reproducirlo pueden instanciar cardToken de la siguiente manera:
`[[CardToken alloc] initWithCardNumber:@"123" expirationMonth:02 expirationYear:21 securityCode:@"123" cardholderName:@"test" docType:@"DNI" docNumber:@"20123321"];`

y luego pedir la validación con paymentMethod perteneciente a VISA
`[cardToken validateSecurityCodeWithPaymentMethod:paymentMethod];`

notar que el número de la tarjeta de crédito es totalmente invalida, pero como es un dato proporcionado por el usuario, puede pasar.

Este es el código que use para solucionar temporalmente el problema:

```
open func validateSecurityCodeWithPaymentMethod(_ paymentMethod: PaymentMethod) -> String? {
    let validSecurityCode = self.validateSecurityCode(securityCode)
    if validSecurityCode != nil {
        return validSecurityCode
    } else {
        guard cardNumber!.characters.count >= 6 else {return "El número de tarjeta que ingresaste es incorrecto"}
        let range = cardNumber!.startIndex ..< cardNumber!.characters.index(cardNumber!.characters.startIndex, offsetBy: 6)
        return validateSecurityCodeWithPaymentMethod(securityCode!, paymentMethod: paymentMethod, bin: cardNumber!.substring(with: range))
    }
}
```

**Comment by demtej** [comment]
Fixed! 
Se fixeo el bug, disponible del pod 2.2.6 en adelante.
Gracias por la colaboración.
