### ISSUE TITLE
MerchantServer.createPreference invierte los parámetros del request

### ISSUE THREAD

**Issue by nsuarezml** [mercadopago/px-ios#452]
Al utilizar el componente `MerchantServer` para crear una preferencia de pago, se invierten los valores del diccionario que se pasa por parámetro, es decir, se envían los valores como claves y las claves como valores. 

### Tipo de componente utilizado
`MerchantServer.createPreference`

### Comportamiento Esperado
Si se pasa como parámetro el siguiente diccionario
```swift
let preferenceBody = ["key1": "value1", "key2": "value2"]
MerchantServer.createPreference(preferenceBody as NSDictionary,
                                        success: { (checkoutPreference) in
                                            // Do something
        }, failure: { (error) in
            //Show error
        })
```
Al realizar el request el body debería ser:
```
{ 
 "key1": "value1",
 "key2": "value2" 
}
```
### Comportamiento Actual
Se está enviando como body del request:
```
{ 
 "value1": "key1",
 "value2": "key2" 
}
```

**Comment by crisyelpegaso** [comment]
Gracias @nsuarezml por reportar el error! Lo tenemos corregido para la próxima versión, que entre hoy o mañana estará disponible, te avisamos, saludos!

**Comment by crisyelpegaso** [comment]
@nsuarezml el fix de este bug se encuentra en la versión 2.2.7 de la SDK

**Comment by nsuarezml** [comment]
@crisyelpegaso genial, gracias!!!
