### ISSUE TITLE
No se borran los Datos al ir para atras en el PaymentVaultViewController

### ISSUE THREAD

**Issue by augustocollerone** [mercadopago/px-ios#642]
### Tipo de componente utilizado
PaymentVaultViewController

### Comportamiento Esperado
Al ir para atras y salir del flujo, todos los datos del flujo anterior deberían borrarse y al iniciar el flujo nuevamente debería hacerlo sin datos guardados

### Comportamiento Actual
Al ir para atras y salir del flujo, cuando se vuelve a iniciar, le quedan datos guardados del flujo anterior.

**Comment by edentorres** [comment]
se resuelve aca #692
