### ISSUE TITLE
Guessing de Tarjetas no funciona

### ISSUE THREAD

**Issue by augustocollerone** [mercadopago/px-ios#643]
### Comportamiento Esperado
Cuando en grupos es seleccionado el tipo de tarjeta (credito/debito) no deberia ser necesario preguntarle al usuario que tipo de tarjeta es.

### Comportamiento Actual
Cuando en grupos se selecciona "Tarjeta de Debito", al momento de pintar la tarjeta la pinta como tarjeta de crédito y ademas al terminar el cardform aparece el CardAdditionalViewController para seleccionar el tipo de tarjeta.
Al seleccionar un tipo de tarjeta vuelve a aparecer la misma pantalla de CardAdditionalViewController en un loop infinito.

**Comment by edentorres** [comment]
Se resuelve aca #668
